AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Async Academy Website and Backend

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name (dev or prod)

  DomainName:
    Type: String
    Default: ""
    Description: (Optional) The domain name for the website. Leave blank for default CloudFront URL.

  CertificateArn:
    Type: String
    Default: ""
    Description: (Optional) ARN of the ACM Certificate. Required if DomainName is provided.

  HostedZoneId:
    Type: String
    Default: ""
    Description: (Optional) Route53 Hosted Zone ID. Required if DomainName is provided.

  # Secrets (NoEcho: true triggers manage.py to look in Secrets Manager)
  StripeSecretKey:
    Type: String
    Description: Stripe Secret Key for processing payments
    NoEcho: true

  StripeEventBusName:
    Type: String
    Description: Name of the Stripe Event Bus (Partner Event Source)
    Default: "default"

  GoogleRecaptchaKey:
    Type: String
    Description: Google Recaptcha Site Key (for verification)
    NoEcho: true

  GoogleApiKey:
    Type: String
    Description: Google API Key for Recaptcha Enterprise
    NoEcho: true

  GoogleProjectId:
    Type: String
    Description: Google Project ID for Recaptcha Enterprise

  VerifiedEmail:
    Type: String
    Description: SES Verified Email Address for sending notifications

  SenderName:
    Type: String
    Default: "Async Academy"
    Description: Friendly name for the email sender (e.g. Async Academy)

  EmailArn:
    Type: String
    Description: ARN of the SES Identity

Globals:
  Function:
    Timeout: 30
    Runtime: python3.14
    Architectures:
      - arm64
    Environment:
      Variables:
        ENV: !Ref Environment
        # Add common env vars here if needed

Conditions:
  HasDomain: !Not [!Equals [!Ref DomainName, ""]]
  IsProd: !Equals [!Ref Environment, "prod"]

Resources:
  # --------------------------------------------------------------------------
  # AWS Budget (Production Only)
  # --------------------------------------------------------------------------
  MonthlyCostBudget:
    Type: AWS::Budgets::Budget
    Condition: IsProd
    Properties:
      Budget:
        BudgetName: !Sub "${AWS::StackName}-Monthly-Budget"
        BudgetLimit:
          Amount: 30
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 20
            ThresholdType: ABSOLUTE_VALUE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: greg@gregorysenyshyn.com
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 30
            ThresholdType: ABSOLUTE_VALUE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: greg@gregorysenyshyn.com

  # --------------------------------------------------------------------------
  # API Gateway
  # --------------------------------------------------------------------------
  WebsiteApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Session-Token'"
        AllowOrigin: "'*'"

  # --------------------------------------------------------------------------
  # S3 Bucket for Website Hosting
  # --------------------------------------------------------------------------
  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !If [HasDomain, !Ref DomainName, !Ref "AWS::NoValue"]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteCloudFrontDistribution}"

  # --------------------------------------------------------------------------
  # CloudFront KeyValueStore and Function (Production Only)
  # --------------------------------------------------------------------------
  ABTestingStore:
    Type: AWS::CloudFront::KeyValueStore
    Condition: IsProd
    Properties:
      Name: !Sub "${AWS::StackName}-ABTestingStore"

  ABTestingFunction:
    Type: AWS::CloudFront::Function
    Condition: IsProd
    Properties:
      Name: !Sub "${AWS::StackName}-ABTestingFunction"
      FunctionCode: !Sub |
        import cf from 'cloudfront';
        import { createKvsHandle } from 'cloudfront-kv-store';
        const kvsHandle = createKvsHandle();

        async function handler(event) {
          const request = event.request;
          const uri = request.uri;
          try {
            const configStr = await kvsHandle.get(uri);
            if (configStr) {
              const config = JSON.parse(configStr);
              if (config.variants && Array.isArray(config.variants)) {
                const totalWeight = config.variants.reduce((sum, v) => sum + (v.weight || 0), 0);
                let random = Math.random() * totalWeight;
                for (const variant of config.variants) {
                  random -= (variant.weight || 0);
                  if (random <= 0) {
                    if (variant.path) {
                      request.uri = variant.path;
                    }
                    break;
                  }
                }
              }
            }
          } catch (err) {
            // Key not found or error, proceed with original request
          }
          return request;
        }
      FunctionConfig:
        Comment: "A/B Testing Function using KeyValueStore"
        Runtime: cloudfront-js-2.0
        KeyValueStoreAssociations:
          - KeyValueStoreArn: !GetAtt ABTestingStore.Arn
      AutoPublish: true

  # --------------------------------------------------------------------------
  # CloudFront Distribution
  # --------------------------------------------------------------------------
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index
        Aliases: !If [HasDomain, [!Ref DomainName], !Ref "AWS::NoValue"]
        ViewerCertificate:
          !If
          - HasDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          FunctionAssociations:
            !If
            - IsProd
            - - EventType: viewer-request
                FunctionARN: !GetAtt ABTestingFunction.FunctionARN
            - !Ref "AWS::NoValue"
        HttpVersion: http2

  # --------------------------------------------------------------------------
  # Route53 Record
  # --------------------------------------------------------------------------
  WebsiteDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt WebsiteCloudFrontDistribution.DomainName

  # --------------------------------------------------------------------------
  # DynamoDB Table for Registrations
  # --------------------------------------------------------------------------
  RegistrationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Registration"
      AttributeDefinitions:
        - AttributeName: payment_id
          AttributeType: S
      KeySchema:
        - AttributeName: payment_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # --------------------------------------------------------------------------
  # DynamoDB Table for Leads
  # --------------------------------------------------------------------------
  LeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Leads"
      AttributeDefinitions:
        - AttributeName: lead_id
          AttributeType: S
      KeySchema:
        - AttributeName: lead_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # --------------------------------------------------------------------------
  # Step Function for Lead Nurture
  # --------------------------------------------------------------------------
  LeadNurtureStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: WaitFirstHour
        States:
          WaitFirstHour:
            Type: Wait
            SecondsPath: "$.wait_time"
            Next: SendWelcomeEmail
          SendWelcomeEmail:
            Type: Task
            Resource: !GetAtt SendNurtureEmailFunction.Arn
            Parameters:
              email.$: "$.email"
              first_name.$: "$.first_name"
              type: "welcome"
            Next: WaitFollowUp
          WaitFollowUp:
            Type: Wait
            Seconds: 259200 # 3 Days
            Next: SendFollowUpEmail
          SendFollowUpEmail:
            Type: Task
            Resource: !GetAtt SendNurtureEmailFunction.Arn
            Parameters:
              email.$: "$.email"
              first_name.$: "$.first_name"
              type: "followup"
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SendNurtureEmailFunction

  # --------------------------------------------------------------------------
  # Lambda Functions
  # --------------------------------------------------------------------------

  # 1. Contact Form Handler
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.contact_form.lambda_handler
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref VerifiedEmail
      Environment:
        Variables:
          VERIFIED_EMAIL: !Ref VerifiedEmail
          SENDER_NAME: !Ref SenderName
          EMAIL_ARN: !Ref EmailArn
          GOOGLE_RECAPTCHA_KEY: !Ref GoogleRecaptchaKey
          GOOGLE_API_KEY: !Ref GoogleApiKey
          GOOGLE_PROJECT_ID: !Ref GoogleProjectId
      Events:
        ContactEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteApi
            Path: /contact
            Method: post

  # 2. Stripe Payment Intent Creator
  CreatePaymentIntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.create_payment_intent.lambda_handler
      Environment:
        Variables:
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
      Events:
        PaymentEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteApi
            Path: /create-payment-intent
            Method: post

  # 3. Registration Submission Handler
  SubmitRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.submit_registration.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RegistrationTable
      Environment:
        Variables:
          REGISTRATION_TABLE: !Ref RegistrationTable
      Events:
        RegisterEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteApi
            Path: /register
            Method: post

  # 4. Lead Capture Handler
  LeadCaptureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.lead_capture.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeadsTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt LeadNurtureStateMachine.Name
      Environment:
        Variables:
          LEADS_TABLE: !Ref LeadsTable
          STATE_MACHINE_ARN: !Ref LeadNurtureStateMachine
          WAIT_TIME: !If [IsProd, "3600", "60"]
      Events:
        LeadEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteApi
            Path: /lead
            Method: post

  # 5. Send Nurture Email Handler (Internal)
  SendNurtureEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.send_nurture_email.lambda_handler
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref VerifiedEmail
      Environment:
        Variables:
          VERIFIED_EMAIL: !Ref VerifiedEmail
          EMAIL_ARN: !Ref EmailArn

  # 6. Stripe Event Handler (EventBridge)
  StripeEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.stripe_event_handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RegistrationTable
        - SESCrudPolicy:
            IdentityName: !Ref VerifiedEmail
      Environment:
        Variables:
          REGISTRATION_TABLE: !Ref RegistrationTable
          SENDER_EMAIL: !Ref VerifiedEmail
          SENDER_ARN: !Ref EmailArn
          API_URL_FOR_EMAIL: !If [HasDomain, !Sub "https://${DomainName}", !Sub "https://${WebsiteCloudFrontDistribution.DomainName}"]
      Events:
        StripeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref StripeEventBusName
            Pattern:
              source:
                - !Ref StripeEventBusName
              detail-type:
                - "Stripe Event"
              detail:
                type:
                  - "payment_intent.succeeded"

  # 7. Get Registration Details
  GetRegistrationDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.backend_snippets.get_registration_details.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RegistrationTable
      Environment:
        Variables:
          REGISTRATION_TABLE: !Ref RegistrationTable
      Events:
        GetDetailsEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref WebsiteApi
            Path: /registration-details
            Method: get

Outputs:
  WebsiteBucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref WebsiteCloudFrontDistribution
  WebsiteURL:
    Description: URL of the website
    Value: !If [HasDomain, !Sub "https://${DomainName}", !Sub "https://${WebsiteCloudFrontDistribution.DomainName}"]
  ApiUrl:
    Description: URL of the API Gateway
    Value: !Sub "https://${WebsiteApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  RegistrationTableArn:
    Description: ARN of the Registration DynamoDB Table
    Value: !GetAtt RegistrationTable.Arn
  ABTestingStoreId:
    Description: Id of the AB Testing KeyValueStore
    Condition: IsProd
    Value: !Ref ABTestingStore
  ABTestingStoreArn:
    Description: ARN of the AB Testing KeyValueStore
    Condition: IsProd
    Value: !GetAtt ABTestingStore.Arn
